sudo: false
language: python
matrix:
  fast_finish: true
  include:

    # Tests
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38

    # Linting 
    - python: "3.4"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=lint
    - python: "3.8"
      env: TOXENV=lint
      
install: pip install -U tox coveralls
script: tox
cache: pip
after_success: coveralls
