sudo: false
language: python
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.8"
      env: TOXENV=lint
install: pip install -U tox coveralls
script: tox
cache: pip
after_success: coveralls
